### ISSUE TITLE
Question: How can I export partial HTML?

### ISSUE THREAD

**Issue by Tiendq** [unroll-io/react-email-editor#1]
Can I export partial HTML e.g. a single row? If there is no function to do it now, where could I look at it to make a quick hack? :)

Thanks,

**Comment by dilantha111** [comment]
well you can select the part you want with your developer tools. If that's opera or chrome it will be ctrl + shift + i. Or you can go with the menu and open the developer tools. Then with html selector you can select the part you want. And right click it and click 'edit as html' All you have to do is copy that code snippet. Hope you get the idea

**Comment by Tiendq** [comment]
I was talking about code. BTW, the there is only your example code here, not the editor itself.

Thanks.
