### ISSUE TITLE
minWidth fixed to 1024px

### ISSUE THREAD

**Issue by aliogaili** [unroll-io/react-email-editor#3]
Hello - first thanks for this great wrapper, really easy to setup.

I'm unable to override the min width property of the iframe and it's getting overflown from the parent container, any idea how to fix this?

 Thanks

**Comment by aliogaili** [comment]
Ok I just used the following CSS

```
#editor iframe {
  min-width: 100% !important;
}

```
But I think it's useful to have that configurable..

**Comment by adeelraza** [comment]
@aliogaili we have it fixed for 1024px because that is the minimum recommended width. Below that, there may not be enough space for the editor to function properly.

**Comment by aliogaili** [comment]
Thanks @adeelraza so it's by design. 

But what are the effects of decreasing the width that you know of? it seems to be working fine with 930px ?

**Comment by adeelraza** [comment]
@aliogaili in most cases, it won't be a problem. However, if your user decides to increase the body width over the usual, then it may become harder to edit the page.
