### ISSUE TITLE
Identifier 'EmailEditorProps' has already been declared.

### ISSUE THREAD

**Issue by genesis-solution** [unroll-io/react-email-editor#338]
I tried to excute this project in my local. by the way, the code doesn't work properly.
When I run the project, an error occur such as above.
I am a new developer that start learning React.
could you check this issue?
![Capture](https://user-images.githubusercontent.com/132243422/235670114-d70f9496-d4b8-4cdd-87c6-62f04694c9bb.PNG)

**Comment by brunolemos** [comment]
@fulldev100 please try `brunolemos-react-email-editor@2.0.3` and let me know if it works well for you.
