### ISSUE TITLE
embed.bundle.js unavailable

### ISSUE THREAD

**Issue by aliogaili** [unroll-io/react-email-editor#5]
The server was unable to fetch the https://designer.unroll.io/assets/embed.bundle.js , it seems that the server was done. 

`GET https://designer.unroll.io/assets/embed.bundle.js net::ERR_ABORTED
`
When I tried the URL, I got Heroku application error. I hope unroll service is reliable with long-term support since I'm planning to integrate it in a commercial app.

**Comment by aliogaili** [comment]
It's back now, so it was only for a minute or so.

**Comment by adeelraza** [comment]
@aliogaili It's currently hosted on Heroku with auto-scaling enabled so it shouldn't be an issue. But we are in the process of moving the user-facing files to a CDN to add even more reliability. Our uptime for the last 60 days has been 99.98%.

**Comment by aliogaili** [comment]
Great, as I stated it was down for a very short period, but I just wanted to bring it to your attention.
